import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import MainNavbar from "./MainNavbar";
import BottomMenu from "@/Components/BottomMenu";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#191919] relative w-full h-full">
        {/* <Image
          src="/assets/img/gridLayout.png"
          width={1000}
          height={800}
          className="w-full h-full object-cover fixed z-0 top-0 left-0 right-0 bottom-0"
          alt="bg-grid"
        /> */}
        <MainNavbar />
        {/* <Navbar /> */}
        {/* <BottomMenu /> */}
        {children}
      </body>
    </html>
  );
}
