import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import MainNavbar from "@/Components/MainNavbar";
import BottomMenu from "@/Components/BottomMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#191919] relative w-full h-full">
        <MainNavbar />
        {/* <Navbar /> */}
        {/* <BottomMenu /> */}
        {children}
      </body>
    </html>
  );
}
